#!/usr/bin/env python3
import re

with open('whitepaper.html', 'r', encoding='utf-8') as f:
    c = f.read()

R = {
    # === Sections 04-14 remaining Korean ===
    # Section 04
    '경제 모델 — LP Opt-in Hedge': 'Economic Model — LP Opt-in Hedge',
    '<!-- ══════════ 04. 경제 모델 ══════════ -->': '<!-- ══════════ 04. ECONOMIC MODEL ══════════ -->',
    '4.1 프리미엄 구조 — LP 자발적 납부': '4.1 Premium Structure — Voluntary LP Contribution',
    'LP는 자신의 수수료 수익에서 일정 비율을 프리미엄으로 납부하고 IL의 일부를 보상받는다. 프리미엄은 LP가 번 것에서 조금 떼는 구조로, TVL 기준 납부보다 심리적 수용성이 높다.': 'LPs pay a premium from a portion of their fee income and receive partial IL compensation. Since premiums come from earned fees rather than principal, psychological acceptance is higher than TVL-based payments.',
    '프리미엄 = LP 수수료 수익의 12%': 'Premium = 12% of LP fee income',
    'TVL 환산 약 2.7% / year': 'Approximately 2.7%/year in TVL terms',
    'Coverage = IL의 35%': 'Coverage = 35% of IL',
    'partial hedge — 보험 풀 안정성 확보': 'partial hedge — ensures insurance pool stability',
    'LP 순혜택 실측 (2020~2025 백테스트):': 'LP Net Benefit (2020~2025 backtest):',
    '수수료의 12%를 납부해도 IL 보상(35%)이 더 크다. 헤지 없이 +4.0%/yr → 헤지 가입 시': 'Even paying 12% of fees, IL compensation (35%) is larger. Without hedge +4.0%/yr → with hedge',
    'LP는 비용을 내고도 연 +3.7%p 추가 수익을 얻는다. IL은 블랙스완 에포크에 집중 발생하며, Coverage 35%의 보상이 평소 프리미엄 12%의 누적 비용을 초과한다.': 'LPs earn an additional +3.7%p annually even after costs. IL concentrates in black swan epochs, and 35% coverage compensation exceeds the cumulative 12% premium cost.',
    'LP 진입 장벽 = 0:': 'LP Entry Barrier = 0:',
    'V4 Hook이 적용된 풀에 유동성만 공급하면 자동 헤지. 별도 가입, 모니터링, 리밸런싱 불필요. Perps 직접 헤지 대비 운영 복잡성을 완전히 제거한': 'Simply provide liquidity to a V4 Hook pool for automatic hedging. No separate enrollment, monitoring, or rebalancing needed. Completely eliminates operational complexity compared to direct Perps hedging —',
    'LP 순혜택 — 실측 269 에포크 검증 결과': 'LP Net Benefit — Verified Across 269 Measured Epochs',
    '2020~2025 실측 ETH 가격 기반(269주, 패닉 33회 포함) 백테스트 결과, <strong>LP는 프리미엄 12%를 납부하고도 미가입 대비 연 +3.7% 추가 수익</strong>을 얻는다.': 'Based on 2020~2025 actual ETH prices (269 weeks, 33 panic events), <strong>LPs earn +3.7% additional annual returns vs. unhedged even after paying 12% premium</strong>.',
    'LP 연간 수익률 비교 (실측 ETH, 5.1년, $10K LP)': 'LP Annual Return Comparison (Actual ETH, 5.1 Years, $10K LP)',
    '헤지 없음': 'No Hedge',
    '헤지 가입': 'Hedged',
    '헤지 효과': 'Hedge Effect',
    '실측 ETH 269주 | 패닉(≤-10%) 33회 포함 | V3 IL ×2.50 | Coverage 35% | Premium 12%': 'Actual ETH 269 weeks | 33 panic events (≤-10%) | V3 IL ×2.50 | Coverage 35% | Premium 12%',
    '수수료 수입': 'Fee Income',
    '프리미엄 지출 (12%)': 'Premium Paid (12%)',
    'IL 발생 (V3 ×2.5)': 'IL Incurred (V3 ×2.5)',
    'IL 보상 수령 (35%)': 'IL Compensation Received (35%)',
    '5.1년 순수익': '5.1-Year Net Profit',
    '연 수익률': 'Annual Return',
    '* $10,000 TVL LP 1명 기준, 실측 ETH 269 에포크 (2020.01~2025.03). LP는 매주 $5.17 납부 → 블랙스완 에포크에서 1회 최대 $216(COVID -38.5%) 돌려받는 보험 구조. 납부 대비 수령이 +$1,928 순혜택.': '* Based on 1 LP with $10,000 TVL, actual ETH 269 epochs (2020.01~2025.03). LP pays $5.17/week → receives up to $216 per black swan epoch (COVID -38.5%). Net benefit +$1,928 over total payments.',
    '실측 수수료 APY 기준 (GeckoTerminal, 2026년 3월 기준)': 'Measured Fee APY (GeckoTerminal, March 2026)',
    '풀': 'Pool',
    '일 거래량': 'Daily Volume',
    '수수료 APY': 'Fee APY',
    '2024 강세 시 ~28%, 조정 시 ~18%': '~28% in 2024 bull, ~18% in correction',
    '2024 강세 시 ~14%, 조정 시 ~8%': '~14% in 2024 bull, ~8% in correction',
    '* 수수료 APY = 일 거래량 × fee tier × 365 / TVL. 시장 상황에 따라 ±30~40% 변동 가능.': '* Fee APY = daily volume × fee tier × 365 / TVL. Can fluctuate ±30~40% depending on market conditions.',
    'LP 수익 시뮬레이션 (ETH/USDC, 연간 기준)': 'LP Return Simulation (ETH/USDC, Annual Basis)',
    '헤지 없음 (강세)': 'No Hedge (Bull)',
    '헤지 적용 (강세)': 'Hedged (Bull)',
    '헤지 없음 (현재)': 'No Hedge (Current)',
    '헤지 적용 (현재)': 'Hedged (Current)',
    '헤지 없음 (약세)': 'No Hedge (Bear)',
    '헤지 적용 (약세)': 'Hedged (Bear)',
    '블랙스완 (ETH -50%)': 'Black Swan (ETH -50%)',
    '손실 69% 방어': '69% loss protection',
    '핵심 인사이트:': 'Key Insight:',
    '강세장에서 헤지 비용은 1.6%에 불과하고, 약세장에서는 오히려 헤지 가입자가 더 버는 구조. 블랙스완 이벤트에서는 -5.4% 손실을 -1.67%로 줄여 손실의 69%를 방어한다.': 'In bull markets, hedge cost is only 1.6%, while in bear markets hedged LPs actually earn more. In black swan events, -5.4% loss is reduced to -1.67%, defending 69% of losses.',
    '4.2 프리미엄 흐름 — Pool 유입 및 배분 구조': '4.2 Premium Flow — Pool Inflow and Distribution Structure',
    'LP 프리미엄과 DEX 현금 납부는 <strong>합산하여 Pool로 유입</strong>된다. BELTA Labs는 유입 합계의 <strong>15%를 우선 공제</strong>하고, 나머지 85%로 IL 지급 · Senior APY · Treasury 적립을 순서대로 운영한다.': 'LP premiums and DEX cash contributions are <strong>combined and flow into the Pool</strong>. BELTA Labs <strong>deducts 15% from the gross inflow</strong>, and the remaining 85% funds IL payouts, Senior APY, and Treasury reserves in order.',
    'LP 프리미엄': 'LP Premium',
    'DEX 현금 납부': 'DEX Cash Contribution',
    'DEX 현금': 'DEX Cash',
    'BELTA Labs': 'BELTA Labs',
    '15% 우선 공제': '15% Priority Deduction',
    'IL 지급': 'IL Payout',
    '① Treasury first-loss': '① Treasury first-loss',
    'Senior 7% APY': 'Senior 7% APY',
    '② 우선 보장': '② Priority guarantee',
    'Treasury': 'Treasury',
    '잉여 전액 적립': 'Surplus fully reserved',
    '③ 초과분 → BELTA Labs': '③ Excess → BELTA Labs',
    '단계': 'Step',
    '유입': 'Inflow',
    '공제': 'Deduction',
    '비율/금액 (Mid fee)': 'Ratio/Amount (Mid fee)',
    '설명': 'Description',
    'LP TVL $120M × 22.4% × 12% + TVL × 2%': 'LP TVL $120M × 22.4% × 12% + TVL × 2%',
    'gross의 15% 우선 공제': '15% priority deduction from gross',
    '이하 Pool 내부 배분': 'Pool internal distribution below',
    '일일 지급 / 상한': 'Daily Payout / Cap',

    # 4.3-4.4
    '프로토콜 수익 시뮬레이션 (Phase 4 정상상태 가정, 연간)': 'Protocol Revenue Simulation (Phase 4 Steady State, Annual)',
    '⚠ 주의:': '⚠ Note:',
    '아래 수치는 Phase 4 정상상태(TVL 100% 달성) 이론 시뮬레이션이며, Section 7 백테스트(v4.4.0, TVL 달성률 15.7%)와는 별도이다. 실제 초기 수익은 백테스트 결과를 참조할 것.': 'The figures below are theoretical simulations for Phase 4 steady state (100% TVL achieved) and are separate from Section 7 backtest (v4.4.0, 15.7% TVL achievement rate). Refer to backtest results for actual early-stage revenue.',
    '수익원': 'Revenue Source',
    '연간': 'Annual',
    '구분': 'Category',
    'BELTA Labs 수입': 'BELTA Labs Income',
    'BELTA Labs 지출': 'BELTA Labs Expense',
    '프로토콜 내부 순환': 'Protocol Internal Circulation',
    '↻ Pool 유입': '↻ Pool Inflow',
    '✚ 수입': '✚ Income',
    '↻ 내부 순환': '↻ Internal Circulation',
    '▼ 지출': '▼ Expense',
    '↻ Senior 귀속': '↻ Senior Attribution',
    '↻ Treasury 적립': '↻ Treasury Reserve',
    'Gross 합계': 'Gross Total',
    '우선': 'Priority',
    '수입 합계': 'Total Income',
    'Treasury 초과분 환원 (연평균)': 'Treasury Surplus Return (annual average)',
    '🏦 BELTA Labs 총수익': '🏦 BELTA Labs Total Revenue',
    '① 15% 공제 + ② Treasury 초과분': '① 15% deduction + ② Treasury surplus',
    '* 연간 기준. DEX 납부: 현금 TVL 2% → Pool 유입. ✚ 수입 = BELTA Labs 현금 유입 / ▼ 지출 = 프로토콜 운영 비용 / ↻ 내부 순환 = Pool 내 회전. Treasury 초과분은 백테스트 5.1년 평균값.': '* Annual basis. DEX contribution: cash TVL 2% → Pool inflow. ✚ Income = BELTA Labs cash inflow / ▼ Expense = protocol operating costs / ↻ Internal = Pool rotation. Treasury surplus is 5.1yr backtest average.',
    '① 15% 공제 기준.': '① Based on 15% deduction.',
    '4.4 장기 모델 — DEX 납부 전환 (Phase 4+)': '4.4 Long-term Model — DEX Contribution Transition (Phase 4+)',
    '파일럿 이후 LP retention 데이터가 축적되고 Pool $20M 기반이 형성되면, Uniswap Foundation과 협력하여 DEX가 수수료 수익의 일부를 프리미엄으로 납부하는 구조로 전환을 목표로 한다.': 'After pilot data on LP retention accumulates and a $20M Pool base is formed, we aim to transition to a structure where DEXes contribute a portion of fee revenue as premiums, in cooperation with the Uniswap Foundation.',
    'DEX가 TVL 2%를 납부해야 하는 이유:': 'Why DEXes should contribute 2% of TVL:',
    'LP 이탈 비용이 2%보다 훨씬 크다.': 'LP attrition costs far exceed 2%.',
    'LP retention 직접 레버리지.': 'Direct LP retention leverage.',
    '규모 비교:': 'Scale comparison:',
    '주체': 'Entity',
    '혜택': 'Benefit',
    'LP 이탈 방지 + 거래량 유지 + 헤지 프로토콜과의 장기 파트너십': 'LP retention + volume maintenance + long-term hedge protocol partnership',
    '안정적 현금 수익 (~$1.5M/yr) + 프로토콜 성장에 따른 수익 확대': 'Stable cash revenue (~$1.5M/yr) + revenue growth with protocol expansion',
    '프리미엄 12% 전 Phase 통일, LP 순혜택 +3.7%/yr': '12% premium unified across all Phases, LP net benefit +3.7%/yr',
    'Phase 4 전환 조건': 'Phase 4 Transition Conditions',
    '조건': 'Condition',
    '최소 Pool 규모': 'Minimum Pool Size',
    '$20M (Phase 3 완료 기준)': '$20M (Phase 3 completion)',
    '12개월 이상 실증 데이터': '12+ months of empirical data',
    '파트너 DEX 협상 개시': 'Partner DEX negotiation start',
    'Phase 3 말 (24개월 시점)': 'End of Phase 3 (24-month mark)',
    '대상 풀': 'Target Pools',
    'ETH/USDC + BTC/USDC + SOL/USDC (Pool $20M 공유)': 'ETH/USDC + BTC/USDC + SOL/USDC (shared $20M Pool)',
    'Phase 4 BELTA Labs 수익 구조 (Pool $20M · LP TVL $120M · Mid fee 22.4%)': 'Phase 4 BELTA Labs Revenue Structure (Pool $20M · LP TVL $120M · Mid fee 22.4%)',
    '현금 기준': 'Cash basis',
    '백테스트 실측 평균 (5.1년)': 'Backtest measured average (5.1 years)',
    '* BELTA Labs 수익 = ① gross의 15% 우선 공제 + ② Treasury 목표 초과분 환원. DEX 현금 납부는 Pool 유입 후 15% 공제 과정에서 일부 귀속.': '* BELTA Labs revenue = ① 15% priority deduction from gross + ② Treasury surplus return. DEX cash contribution partially allocated during 15% deduction from Pool inflow.',

    # Section 05
    '<!-- ══════════ 05. 자본 구조 ══════════ -->': '<!-- ══════════ 05. CAPITAL STRUCTURE ══════════ -->',
    '자본 구조 — Underwriter Pool': 'Capital Structure — Underwriter Pool',
    '5.1 Phase별 풀 구조 개요': '5.1 Pool Structure Overview by Phase',
    'BELTA IL Hedge Protocol의 자본 구조는 성장 단계에 따라 두 가지 구조로 운영된다. <strong>Phase 1~2는 단일 Underwriter Pool</strong>로 구조를 단순화하고, <strong>Phase 3~4에서 Treasury / Senior 이중 풀</strong>로 전환하여 리스크를 분리한다.': "BELTA IL Hedge Protocol's capital structure operates in two modes by growth stage. <strong>Phase 1~2 uses a single Underwriter Pool</strong> for structural simplicity, transitioning to a <strong>Treasury / Senior dual pool in Phase 3~4</strong> to segregate risk.",
    '풀 구조': 'Pool Structure',
    '단일 Underwriter Pool': 'Single Underwriter Pool',
    'Treasury / Senior 이중 풀': 'Treasury / Senior Dual Pool',
    'Treasury 개념': 'Treasury Concept',
    '없음 (전체 Pool)': 'None (entire Pool)',
    'Senior의 20% (first-loss)': '20% of Senior (first-loss)',
    'Senior APY 목표': 'Senior APY Target',
    '5% (Phase 1) / 6% (Phase 2)': '5% (Phase 1) / 6% (Phase 2)',
    '7% (Phase 3~4)': '7% (Phase 3~4)',
    'LP 프리미엄율': 'LP Premium Rate',
    'fee의 12%': '12% of fees',
    '12% (전 Phase 통일)': '12% (unified across all Phases)',
    'Pool 규모': 'Pool Size',
    '— (P1 Testnet) / $100K (P2)': '— (P1 Testnet) / $100K (P2)',
    '$10M (P3) / $20M (P4)': '$10M (P3) / $20M (P4)',
    '5.2 단일 풀 구조 (Phase 1~2)': '5.2 Single Pool Structure (Phase 1~2)',
    '파일럿 단계에서는 Treasury / Senior 구분 없이 단일 Underwriter Pool을 운영한다. Pool 전체가 Aave/Morpho 자체 운용 수익과 LP 프리미엄을 수취하며, IL 지급 발생 시 Pool 전체에서 충당한다.': 'During pilot phase, a single Underwriter Pool operates without Treasury/Senior distinction. The entire Pool receives Aave/Morpho self-managed returns and LP premiums, with IL payouts funded from the entire Pool.',
    'LP 수수료': 'LP Fees',
    '연 22.4%': '22.4%/yr',
    'Gross Premium': 'Gross Premium',
    '단일 Pool': 'Single Pool',
    'Aave 5% + Net Premium': 'Aave 5% + Net Premium',
    '설정': 'Setting',
    'Aave/Morpho 운용': 'Aave/Morpho Operation',
    '목표 Pool CAGR': 'Target Pool CAGR',
    '프리미엄율': 'Premium Rate',
    'IL 도덕적 해이 방지': 'IL moral hazard prevention',
    '부분 헤지로 Pool 안정성 확보': 'Pool stability through partial hedging',
    '5.2.1 유동성 리스크 대응 — Liquid Reserve + Epoch 정산': '5.2.1 Liquidity Risk Response — Liquid Reserve + Epoch Settlement',
    'Pool 전체를 Aave/Morpho에 예치할 경우, 블랙스완 시 IL 지급 요청과 Aave 유동성 부족이 동시에 발생할 수 있다. 이를 방어하기 위해 두 가지 메커니즘을 병행한다.': 'When the entire Pool is deposited in Aave/Morpho, IL payout requests and Aave liquidity shortages can occur simultaneously during black swans. Two mechanisms are employed to defend against this.',
    '① Liquid Reserve (유동성 준비금)': '① Liquid Reserve',
    'Pool의 10%를 USDC 현금으로 상시 유지. 소규모 IL 지급은 즉시 현금 지급, 대형 이벤트만 Aave 인출 처리.': '10% of Pool maintained as USDC cash at all times. Small IL payouts via immediate cash, large events only via Aave withdrawal.',
    '② Epoch 정산 방식': '② Epoch Settlement Method',
    'IL을 실시간이 아닌 주기적(Epoch) 단위로 배치 정산. Aave 인출 타이밍을 계획적으로 관리하여 유동성 충격 최소화.': 'Batch-settle IL periodically (per Epoch) rather than real-time. Manage Aave withdrawal timing to minimize liquidity shocks.',
    '결과:': 'Result:',
    '블랙스완 상황에서도 IL 지급 불이행 리스크를 구조적으로 차단.': 'Structurally prevents IL payment default risk even during black swan events.',
    '5.3 이중 풀 구조 (Phase 3~4) — 프리미엄 흐름 및 IL 지급': '5.3 Dual Pool Structure (Phase 3~4) — Premium Flow and IL Payouts',
    'LP 프리미엄과 DEX 현금 납부 합산에서 15%를 BELTA Labs가 우선 공제한다. 나머지 85%(net)와 Aave 수익으로 IL 지급 · Senior APY · Treasury 적립을 순서대로 운영한다. Senior는 <strong>복리 거치형</strong>으로 운영 — 이자가 sb에 매일 적립되며 원금+이자가 함께 IL 버퍼 역할을 한다.': 'BELTA Labs deducts 15% from the combined LP premiums and DEX cash contributions. The remaining 85% (net) plus Aave yields fund IL payouts, Senior APY, and Treasury reserves in order. Senior operates as a <strong>compound accrual</strong> — interest accrues daily to sb, with principal+interest together serving as IL buffer.',
    '백테스트 v4.4.0 실측 결과는 Section 7 참조. 백테스트에서 Phase 3~4 Treasury CAGR +10.2%, BELTA Labs 수입 $31,565/yr (TVL 달성률 15.7% 반영).': 'See Section 7 for backtest v4.4.0 results. In backtest, Phase 3~4 Treasury CAGR +10.2%, BELTA Labs income $31,565/yr (reflecting 15.7% TVL achievement rate).',
    '순서': 'Order',
    'gross (LP프리미엄 + DEX현금)': 'Gross (LP Premium + DEX Cash)',
    'Aave 수익 (Senior × 5%)': 'Aave Yield (Senior × 5%)',
    'Senior 복리 잔액 기준 매일 적립': 'Daily accrual based on Senior compound balance',
    'BELTA Labs 15%': 'BELTA Labs 15%',
    'gross 우선 공제 → BELTA Labs': 'Gross priority deduction → BELTA Labs',
    '① IL 지급': '① IL Payout',
    'Coverage 35% (Epoch 정산)': 'Coverage 35% (Epoch Settlement)',
    'Treasury first-loss → Senior 순': 'Treasury first-loss → then Senior',
    '② Senior': '② Senior',
    'topup (7%−Aave 5% = 2%)': 'Topup (7%−Aave 5% = 2%)',
    'net에서 우선 충당, sb에 복리 적립': 'Priority funded from net, compound accrual to sb',
    '③ Treasury': '③ Treasury',
    '순 잉여 적립': 'Net surplus reserve',
    '목표 초과분 ~$984K → BELTA Labs, 나머지 잔류': 'Surplus over target ~$984K → BELTA Labs, remainder stays',
    '비중': 'Weight',
    '목표 수익': 'Target Return',
    '특성': 'Characteristics',
    '블랙스완 first-loss 흡수 후 회복. 초과분 BELTA Labs 환원': 'Absorbs black swan first-loss then recovers. Surplus returned to BELTA Labs',
    '복리 거치형 — Aave 5% + 프리미엄 2% 매일 sb 적립': 'Compound accrual — Aave 5% + premium 2% daily sb accrual',
    '일반 투자자': 'General Investors',
    'BELTA 홀더': 'BELTA Holders',
    '* Treasury=CAGR (복리 성장, first-loss 흡수 후 회복), Senior=APY (복리 거치, 원금+이자 함께 성장).': '* Treasury=CAGR (compound growth, recovers after first-loss absorption), Senior=APY (compound accrual, principal+interest grow together).',
    '5.4 Phase 2→3 전환 — 강제분할 및 BELTA 토큰 지급': '5.4 Phase 2→3 Transition — Forced Split and BELTA Token Distribution',
    'Phase 2 말 단일 풀이 $2M 이상 축적되면, 강제분할을 통해 이중 풀 구조로 전환한다. 기존 투자자는 Treasury 전환분에 대해 BELTA 토큰으로 보상받는다.': 'When the single pool exceeds $2M at end of Phase 2, it transitions to dual pool structure via forced split. Existing investors receive BELTA tokens for their Treasury conversion portion.',
    '강제분할 방식:': 'Forced Split Method:',
    'Phase 2 말 Pool 잔액의 20% → Treasury Pool 전환': 'End of Phase 2: 20% of Pool balance → Treasury Pool conversion',
    'Phase 2 말 Pool 잔액의 80% → Senior Pool 전환': 'End of Phase 2: 80% of Pool balance → Senior Pool conversion',
    '→ <strong>20% 전환분에 대해 BELTA 토큰 지급</strong> (프로토콜 수익 참여권 확보, 추후 매도 가능)': '→ <strong>BELTA tokens issued for the 20% conversion</strong> (protocol revenue participation rights, tradeable later)',
    '⭐ Phase 1~2 Early Investor 인센티브': '⭐ Phase 1~2 Early Investor Incentive',
    '5.5 Treasury 차익 분배 메커니즘': '5.5 Treasury Surplus Distribution Mechanism',
    'Senior 7% APY 지급 후 잔여 수익은 Treasury 버퍼 상태에 따라 자동 배분된다.': 'Remaining revenue after Senior 7% APY payout is automatically distributed based on Treasury buffer status.',
    '5.6 자기 치유(Self-Healing) 메커니즘': '5.6 Self-Healing Mechanism',
    'Pool 잔액이 초기 대비 감소할 경우 프로토콜 수수료를 자동 조정하여 회복을 가속화한다.': 'When Pool balance decreases from initial level, protocol fees are automatically adjusted to accelerate recovery.',
    'Pool 건강도': 'Pool Health',
    '프로토콜 수수료': 'Protocol Fee',
    '상태': 'Status',
    '정상': 'Normal',
    '정상 운영': 'Normal Operation',
    '주의': 'Caution',
    '회복 가속': 'Accelerated Recovery',
    '경고': 'Warning',
    '긴급 회복': 'Emergency Recovery',
    '긴급': 'Critical',
    '최대 회복': 'Maximum Recovery',
    '5.7 LP TVL 측정 방식 — 가격 연동 모델': '5.7 LP TVL Measurement — Price-Linked Model',
    '백테스트 및 프로토콜 내부에서 LP TVL은 <strong>고정 달러값이 아닌 토큰 수량 × 현재 가격</strong>으로 산출한다. 이 방식은 시장 하락 시 TVL 변동의 실제 원인을 정확히 반영한다.': 'In backtests and protocol internals, LP TVL is calculated as <strong>token quantity × current price rather than fixed dollar values</strong>. This method accurately reflects the true cause of TVL changes during market declines.',

    # Section 05b - BELTA Token
    '<!-- ══════════ 05b. BELTA 토큰 ══════════ -->': '<!-- ══════════ 05b. BELTA TOKEN ══════════ -->',
    'BELTA 거버넌스 토큰': 'BELTA Governance Token',
    '5.8 BELTA 토큰 역할 (Phase별)': '5.8 BELTA Token Role (by Phase)',
    'BELTA는 프로토콜의 거버넌스 토큰이자 Treasury 수익 참여 토큰이다. Phase에 따라 역할이 확장된다.': 'BELTA is the protocol governance token and Treasury revenue participation token. Its role expands by Phase.',
    '방식': 'Method',
    'A방식 — Treasury 수익 참여 토큰': 'Method A — Treasury Revenue Participation Token',
    'BELTA 예치 = Treasury 수익 분배권 취득. xBELTA 환율 상승으로 수익 반영, 손실 시 환율 하락.': 'BELTA staking = Treasury revenue distribution rights. Revenue reflected via xBELTA exchange rate increase, rate decreases on losses.',
    'C방식 — 수익 참여 + 거버넌스': 'Method C — Revenue Participation + Governance',
    '프로토콜 수익 참여권 + 파라미터 투표권 (커버리지율, 프리미엄율 등)': 'Protocol revenue participation + parameter voting rights (coverage rate, premium rate, etc.)',
    '5.9 발행 구조': '5.9 Issuance Structure',
    '총 발행량': 'Total Supply',
    'Treasury 인센티브': 'Treasury Incentive',
    '예치 보상 · 장기 유동성': 'Staking rewards · Long-term liquidity',
    '팀 / 파운더': 'Team / Founder',
    '4년 락업 · 1년 클리프': '4-year lockup · 1-year cliff',
    '생태계 / 커뮤니티': 'Ecosystem / Community',
    '파트너십 20% + 커뮤니티 10% + Reserve 10%': 'Partnership 20% + Community 10% + Reserve 10%',
    '세부 내역': 'Details',
    'Treasury 참여 인센티브': 'Treasury Participation Incentive',
    '예치 보상, 장기 유동성 공급자 인센티브': 'Staking rewards, long-term liquidity provider incentives',
    '4년 락업, 1년 클리프 (DeFi 표준)': '4-year lockup, 1-year cliff (DeFi standard)',
    '생태계 / 파트너십': 'Ecosystem / Partnership',
    'DEX 협상, 보안 감사 기관, 전략 파트너': 'DEX negotiations, security audit firms, strategic partners',
    '커뮤니티 / 에어드롭': 'Community / Airdrop',
    '초기 LP 유치, 프로토콜 홍보': 'Early LP acquisition, protocol promotion',
    '비상 Treasury 보충, 전략적 보유': 'Emergency Treasury replenishment, strategic reserves',

    # Section 06
    '<!-- ══════════ 06. 수학적 프레임워크 ══════════ -->': '<!-- ══════════ 06. MATHEMATICAL FRAMEWORK ══════════ -->',
    '수학적 프레임워크 — IL 계산': 'Mathematical Framework — IL Calculation',
    '6.1 V3 IL 보정 공식': '6.1 V3 IL Correction Formula',
    'Uniswap V3의 집중 유동성 범위 [Pa, Pb]에서 IL은 V2 대비 증폭된다.': 'IL is amplified vs V2 in Uniswap V3 concentrated liquidity range [Pa, Pb].',
    '6.2 온체인 IL 계산 — Epoch 기반 누적 방식': '6.2 On-chain IL Calculation — Epoch-based Cumulative Method',
    '단순 진입/청산 가격 비교는 가격이 범위 밖으로 나갔다 돌아오는 경우 IL을 과소 측정한다. BELTA는 epoch 기반 누적 방식을 사용하여 중간 경로의 IL을 정확히 반영한다.': 'Simple entry/exit price comparison underestimates IL when price moves out of range and returns. BELTA uses epoch-based cumulative method to accurately reflect IL along the intermediate path.',
    '// afterAddLiquidity: 포지션 스냅샷': '// afterAddLiquidity: Position Snapshot',
    '// afterRemoveLiquidity: IL 계산 및 정산': '// afterRemoveLiquidity: IL Calculation and Settlement',
    '6.3 범위 이탈 케이스 처리': '6.3 Range Exit Case Handling',
    '가격이 포지션 범위를 이탈하면 LP 포지션은 단일 토큰으로 변환된다. 이 케이스는 V4 Hook의 afterSwap에서 매 스왑마다 포지션 상태를 업데이트하여 처리한다.': 'When price exits the position range, LP position converts to a single token. This case is handled by updating position state with every swap in V4 Hook afterSwap.',
    '케이스': 'Case',
    '처리 방식': 'Handling Method',
    '가격 범위 내 유지': 'Price stays in range',
    '청산 시 점 비교 (entry → exit)': 'Point comparison at removal (entry → exit)',
    '범위 이탈 후 재진입': 'Range exit then re-entry',
    'Epoch 누적: 이탈 시 중간 정산 후 재진입': 'Epoch cumulative: intermediate settlement on exit then re-entry',
    '범위 이탈 후 미복귀': 'Range exit without return',
    '청산 시 단일 토큰 가치로 IL 계산': 'IL calculated at single-token value on removal',
    '부분 청산': 'Partial removal',
    'Liquidity 비율로 proportional IL 계산': 'Proportional IL calculation by liquidity ratio',
    '6.4 이벤트 스파이크 모델 (백테스트 전용)': '6.4 Event Spike Model (Backtest Only)',
    '6.5 변동성 조정 프리미엄': '6.5 Volatility-Adjusted Premium',

    # Section 07
    '<!-- ══════════ 07. 백테스트 ══════════ -->': '<!-- ══════════ 07. BACKTEST ══════════ -->',
    '백테스트 결과 — 실측 ETH 가격 + 3-Layer (v5.0.1)': 'Backtest Results — Real ETH Prices + 3-Layer (v5.0.1)',
    'v5.0.1 핵심:': 'v5.0.1 Key Points:',
    '① 실측 ETH/USD 주간 종가 270개 (2020.01~2025.03, Etherscan/CoinGecko 기반) ② BIS 기반 LP 코호트 모델 ③ Layer 1 Dynamic Fee + Layer 3 Perps Hedging 모델링 ④ Senior topup 정상 반영 ⑤ Sliding window 스트레스 테스트 (전 구간 4주 간격)': '① 270 actual ETH/USD weekly closes (2020.01~2025.03, Etherscan/CoinGecko) ② BIS-based LP cohort model ③ Layer 1 Dynamic Fee + Layer 3 Perps Hedging modeling ④ Senior topup properly reflected ⑤ Sliding window stress test (4-week intervals across entire period)',
    '7.1 테스트 개요': '7.1 Test Overview',
    '기간': 'Period',
    '가격 데이터': 'Price Data',
    '실측 ETH/USD 주간 종가 (Etherscan/CoinGecko 교차 검증)': 'Actual ETH/USD weekly closes (Etherscan/CoinGecko cross-verified)',
    '주간 수익률 범위': 'Weekly Return Range',
    '프리미엄율': 'Premium Rate',
    'fee의 12% (전 Phase 통일)': '12% of fees (unified across all Phases)',
    'IL의 35%': '35% of IL',
    'gross의 15%': '15% of gross',
    'IL 배율 (BIS 가중평균)': 'IL Multiplier (BIS weighted average)',
    '×2.50 (기관 80%×2.8 + 액티브 15%×1.5 + 패시브 5%×0.7)': '×2.50 (institutional 80%×2.8 + active 15%×1.5 + passive 5%×0.7)',
    'Layer 1 (Dynamic Fee)': 'Layer 1 (Dynamic Fee)',
    '변동성 ≥5%: ×1.5 / ≥10%: ×2.5 / ≥20%: ×4.0': 'Volatility ≥5%: ×1.5 / ≥10%: ×2.5 / ≥20%: ×4.0',
    'Layer 3 (Perps Hedging)': 'Layer 3 (Perps Hedging)',
    '효과 60% / 헤지비율 50% / 펀딩 2%/yr': 'Effectiveness 60% / hedge ratio 50% / funding 2%/yr',
    'TVL 모델': 'TVL Model',
    '100% (프로토콜 구조 검증용)': '100% (for protocol structure verification)',
    '스트레스 테스트': 'Stress Test',
    'Sliding window (4주 간격, 전 구간 스캔)': 'Sliding window (4-week intervals, full period scan)',
    '7.2 Phase별 핵심 성과': '7.2 Key Performance by Phase',
    '손익비': 'P/L Ratio',
    '* Sliding window: 4주 간격으로 전체 269 에포크를 스캔한 결과의 median/worst/best. 손익비 = 수입 > IL인 에포크 비율. Senior는 전 Phase 원금+이자 보호.': '* Sliding window: median/worst/best from scanning all 269 epochs at 4-week intervals. P/L Ratio = percentage of epochs where income > IL. Senior principal+interest protected across all Phases.',
    '6개월': '6 months',
    'DEX 없음': 'No DEX',
    '7.3 Phase별 재무 상세 (Median Window)': '7.3 Detailed Financials by Phase (Median Window)',
    '금액': 'Amount',
    '파일럿 $100K · 6개월': 'Pilot $100K · 6 Months',
    '수입': 'Income',
    'IL 지급 (L3 후)': 'IL Payout (after L3)',
    'IL/수입': 'IL/Income',
    '수입 $10,207': 'Income $10,207',
    '오픈마켓 $10M · 2년 · DEX 없음': 'Open Market $10M · 2 Years · No DEX',
    'Pool 전체': 'Total Pool',
    '수입 합계 $4,310,811': 'Total Income $4,310,811',
    'Raw IL $6.15M → L3 절감 $2.33M (38%)': 'Raw IL $6.15M → L3 savings $2.33M (38%)',
    'L3 펀딩비용': 'L3 Funding Cost',
    'Perps 숏 유지 비용': 'Perps short maintenance cost',
    'Senior topup': 'Senior Topup',
    '7%-5%=2% gap Treasury 부담': '7%-5%=2% gap borne by Treasury',
    'Phase 3 Treasury 적자의 의미:': 'Meaning of Phase 3 Treasury Deficit:',
    'DEX 수입 없이 LP 프리미엄만으로 2년간 운영하면 Treasury는 -31%/yr 적자이다. 이는 <strong>설계된 소모 구간</strong>이며, VC 자본(Section 10.3)으로 Treasury를 충분히 확보한 후 Phase 4 DEX 협약으로 전환하는 것이 전제 조건이다. Pool 전체(Treasury+Senior)는 +$152K 흑자이며 Senior는 +7.2%/yr 완전 보호.': 'Operating for 2 years on LP premiums alone without DEX revenue results in Treasury -31%/yr deficit. This is a <strong>designed burn period</strong>, with the prerequisite being sufficient Treasury secured via VC capital (Section 10.3) before transitioning to Phase 4 DEX agreements. Total Pool (Treasury+Senior) is +$152K surplus and Senior is fully protected at +7.2%/yr.',
    'DEX 납부 $20M · LP TVL $120M · DEX 2%': 'DEX Contribution $20M · LP TVL $120M · DEX 2%',
    'LP 12% + DEX 2% 합산 (Proto Fee 15% 차감 후)': 'LP 12% + DEX 2% combined (after 15% Proto Fee deduction)',
    '수입 합계 $16,711,041': 'Total Income $16,711,041',
    'Raw IL $18.46M → L3 절감 $6.60M (36%)': 'Raw IL $18.46M → L3 savings $6.60M (36%)',
    '① Phase 4에서 DEX 2% 유입이 흑자 전환의 결정적 요인. LP 프리미엄 12% + DEX 2% = 수입률 ~4.7%/yr(TVL 대비) → IL/수입 0.89x.': '① DEX 2% inflow in Phase 4 is the decisive factor for profitability. LP premium 12% + DEX 2% = income rate ~4.7%/yr (vs TVL) → IL/Income 0.89x.',
    '② Layer 3가 Raw IL의 36%를 상쇄. COVID(-38.5%) 급의 블랙스완에서 효과 극대화.': '② Layer 3 offsets 36% of Raw IL. Effect maximized during COVID(-38.5%) level black swans.',
    '③ Senior +7.2%/yr — Treasury가 first-loss를 부담하므로 Senior는 전 구간 보호. worst window에서도 Senior 원금 유지.': '③ Senior +7.2%/yr — Treasury bears first-loss so Senior is protected across all periods. Senior principal preserved even in worst window.',
    '④ Phase 3 적자는 DEX 수입 없는 구조적 한계. VC 자본으로 버티는 설계된 투자 구간.': '④ Phase 3 deficit is a structural limitation without DEX revenue. A designed investment period sustained by VC capital.',
    '7.4 LP 관점 — 헤지 가입의 실질 효과': '7.4 LP Perspective — Real Effect of Hedge Enrollment',
    '$10,000 TVL LP 1명이 5.1년간 헤지에 가입했을 때의 실측 기반 손익.': 'Measured profit/loss for 1 LP with $10,000 TVL enrolled in hedge for 5.1 years.',
    '수수료 수입 (gross)': 'Fee Income (gross)',
    '프리미엄 지출 (fee의 12%)': 'Premium Paid (12% of fees)',
    '실제 IL 발생 (V3 ×2.5)': 'Actual IL Incurred (V3 ×2.5)',
    '연간 수익률 (TVL 대비)': 'Annual Return (vs TVL)',
    '* 실측 ETH 가격 기반 (2020~2025). 수수료 APY 22.4%, V3 IL multiplier ×2.50 (BIS 가중평균). LP는 매주 $5.17(수수료의 12%) 납부하고, 블랙스완 에포크에서 1회 최대 $216 (COVID -38.5% 주) 돌려받는 구조.': '* Based on actual ETH prices (2020~2025). Fee APY 22.4%, V3 IL multiplier ×2.50 (BIS weighted avg). LP pays $5.17/week (12% of fees), receives up to $216 per black swan epoch (COVID -38.5% week).',
    '7.5 모델 한계 및 보수적 가정': '7.5 Model Limitations and Conservative Assumptions',
    '투명성을 위해 명시하는 모델 한계:': 'Model limitations disclosed for transparency:',
    '가격 데이터:': 'Price Data:',
    '실측 주간 종가 270개를 수동 복원. 일중(intraday) 변동 미반영. 프로덕션 시 API 일별 데이터로 교체 권장.': '270 weekly closes manually restored. Intraday volatility not reflected. Recommend replacing with API daily data in production.',
    'IL 배율:': 'IL Multiplier:',
    'BIS 가중평균 ×2.50 단일값 사용. 실제로는 LP별 range 설정에 따라 ×0.7~×4.5 분산.': 'Single BIS weighted average ×2.50 used. In reality, ranges from ×0.7~×4.5 depending on LP range settings.',
    'Layer 3 effectiveness 60%:': 'Layer 3 effectiveness 60%:',
    '보수적 가정. 실제 Perps 시장 유동성, 슬리피지, 펀딩레이트 변동에 따라 40~80% 범위.': 'Conservative assumption. Actually ranges 40~80% depending on Perps market liquidity, slippage, and funding rate fluctuations.',
    'TVL 100% 가정:': 'TVL 100% assumption:',
    '프로토콜 구조 검증 목적. 실제 초기 채택률은 15~30%로 시작하여 점진적 상승 예상.': 'For protocol structure verification. Actual initial adoption rate expected to start at 15~30% and gradually increase.',
    'Worst window에서 Treasury 100% 소진 가능:': 'Treasury 100% depletion possible in worst window:',
    '2022 LUNA+FTX 연속 충격 구간에서 발생. Senior가 IL을 이어받아 Pool 전체는 보존되나, Treasury 투자자는 전액 손실 가능.': 'Occurs during 2022 LUNA+FTX consecutive shock period. Senior absorbs IL so total Pool is preserved, but Treasury investors may face total loss.',

    # Section 08
    '<!-- ══════════ 08. 언더라이팅 ══════════ -->': '<!-- ══════════ 08. UNDERWRITING ══════════ -->',
    '언더라이팅 기준 — Adverse Selection 방어': 'Underwriting Criteria — Adverse Selection Defense',
    '8.1 언더라이팅 규칙': '8.1 Underwriting Rules',
    '기준': 'Criteria',
    '반려 이유': 'Rejection Reason',
    '범위 폭 (Range Width)': 'Range Width',
    '±10% 이하 Narrow 반려': 'Reject Narrow ±10% or less',
    'IL 증폭 과다 — 보험 수리적 손해': 'Excessive IL amplification — actuarially unprofitable',
    '최소 포지션 크기': 'Minimum Position Size',
    '$10,000 이상': '$10,000 or more',
    '소규모 포지션 가스비 대비 비효율': 'Small positions inefficient vs gas costs',
    '최소 보유 기간': 'Minimum Hold Period',
    '72시간 이상 유지 조건': 'Must hold 72+ hours',
    '단기 투기적 헤지 방지': 'Prevent short-term speculative hedging',
    '포지션 연령': 'Position Age',
    '생성 후 1시간 경과': '1 hour after creation',
    '즉시 헤지 후 즉시 청산 방지': 'Prevent immediate hedge then immediate exit',
    '8.2 역선택 방어 효과': '8.2 Adverse Selection Defense Effect',
    'Narrow 범위 LP는 전체 TVL의 약 20%를 차지하지만 IL 발생 비용은 불균형적으로 높다. 이를 반려함으로써 언더라이터 수익성이 구조적으로 개선된다.': 'Narrow range LPs account for ~20% of total TVL but IL costs are disproportionately high. Rejecting them structurally improves underwriter profitability.',
    '적용 조건': 'Applied Condition',
    '커버 TVL': 'Covered TVL',
    '연간 IL 비용': 'Annual IL Cost',
    '프리미엄 대비 IL': 'IL vs Premium',
    '필터 없음 (전체 커버)': 'No Filter (full coverage)',
    'Narrow 반려 적용': 'Narrow Rejection Applied',
    '* 프리미엄 TVL 환산 2.69% (fee 22.4% × 12%) 기준, Coverage 35% 적용': '* Premium TVL equivalent 2.69% (fee 22.4% × 12%), Coverage 35% applied',

    # Section 09
    '<!-- ══════════ 09. 리스크 공시 ══════════ -->': '<!-- ══════════ 09. RISK DISCLOSURE ══════════ -->',
    '리스크 공시 — Underwriter 손실 가능성': 'Risk Disclosure — Underwriter Loss Scenarios',
}

for old, new in R.items():
    c = c.replace(old, new)

with open('whitepaper.html', 'w', encoding='utf-8') as f:
    f.write(c)

import sys
sys.stdout.reconfigure(encoding='utf-8')
korean_chars = re.findall('[가-힣]', c[c.find('<body>'):])
print(f'Korean chars remaining: {len(korean_chars)}')
